on:
  workflow_dispatch:
  push:
    paths:
      - .github/**
      - plugin/**

name: Build plugin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y%m%d%H%M%S')"

      - name: Build
        run: |
          cd plugin
          ./build.sh
          cd ..
      - name: Upload binaries
        run: |
          set -x
          tag_name="0.0.0-dev-${{ steps.date.outputs.date }}"
          hub release create -a "plugin/armv7-unknown-linux-gnueabihf.wplplugin" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
