on:
  - workflow_dispatch
  - push

name: Build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm

      - name: Install cross-compiler tools
        run: |
          sudo apt-get install gcc-9-arm-linux-gnueabihf gcc-arm-linux-gnueabihf libc6-dev-i386

      - name: Build
        run: ./build.sh
        env:
          LIBCLANG_PATH: ${{ runner.temp }}/llvm/lib
          LLVM_CONFIG_PATH: ${{ runner.temp }}/llvm/bin/llvm-config
          CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: /usr/bin/arm-linux-gnueabihf-gcc

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 0.0.0-dev-${{ github.sha }}
          artifacts: libwallaby.zip
