on:
  - workflow_dispatch
  - push

name: Build plugin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y%m%d%H%M%S')"

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm

      - name: Install cross-compiler tools
        run: |
          sudo apt-get install gcc-9-arm-linux-gnueabihf gcc-arm-linux-gnueabihf libc6-dev-i386

      - name: Build
        run: ./build.sh
        env:
          LIBCLANG_PATH: ${{ runner.temp }}/llvm/lib
          LLVM_CONFIG_PATH: ${{ runner.temp }}/llvm/bin/llvm-config
          CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: /usr/bin/arm-linux-gnueabihf-gcc

      - name: Upload binaries
        run: |
          set -x
          tag_name="0.0.0-dev-${{ steps.date.outputs.date }}"
          hub release create -a "armv7-unknown-linux-gnueabihf.wplplugin" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
